/*================================================================================================================================================
                                                                         IMAGES
  ==============================================================================================================================================*/
#include "image/other/logo.h"
#include "image/other/logoSmall.h"
#include "image/other/battery.h"
#include "image/other/update35.h"


#include "image/deviceIcons/door.h"
#include "image/deviceIcons/garageDoor.h"
#include "image/deviceIcons/gate.h"
#include "image/deviceIcons/humidity.h"
#include "image/deviceIcons/light.h"
#include "image/deviceIcons/pressure.h"
#include "image/deviceIcons/rollerShutter.h"
#include "image/deviceIcons/thermometer.h"
#include "image/deviceIcons/window.h"
#include "image/deviceIcons/wirelessPlug.h"
#include "image/deviceIcons/lock.h"
#include "image/deviceIcons/bathroom.h"
#include "image/deviceIcons/bedroom.h"
#include "image/deviceIcons/fan.h"
#include "image/deviceIcons/garden.h"
#include "image/deviceIcons/heater.h"
#include "image/deviceIcons/home.h"
#include "image/deviceIcons/kitchen.h"
#include "image/deviceIcons/lounge.h"
#include "image/deviceIcons/powerCounter.h"
#include "image/deviceIcons/stove.h"
#include "image/deviceIcons/swimmingPool.h"
#include "image/deviceIcons/waterCounter.h"


#include "image/weatherIcons/twoClouds.h"
#include "image/weatherIcons/clear.h"
#include "image/weatherIcons/clearNight.h"
#include "image/weatherIcons/cloudy.h"
#include "image/weatherIcons/fog.h"
#include "image/weatherIcons/hail.h"
#include "image/weatherIcons/partlyCloudy.h"
#include "image/weatherIcons/rainy.h"
#include "image/weatherIcons/rainyCloudy.h"
#include "image/weatherIcons/snowy.h"
#include "image/weatherIcons/storm.h"
#include "image/weatherIcons/stormRainy.h"
#include "image/weatherIcons/windy.h"


#include "image/displayLines/line960x1.h"
#include "image/displayLines/line960x2.h"
#include "image/displayLines/line960x3.h"
#include "image/displayLines/line440x1.h"
#include "image/displayLines/line440x2.h"
#include "image/displayLines/line100x2.h"



/*================================================================================================================================================
                                                                          FONTS
  ==============================================================================================================================================*/
#include "font/firasans.h"

//#include "font/font2/opensans6.h"
//#include "font/font2/opensans8.h"
//#include "font/font2/opensans8b.h"
//#include "font/font2/opensans9.h"
//#include "font/font2/opensans9b.h"
#include "font/font2/opensans10.h"
//#include "font/font2/opensans10b.h"
//#include "font/font2/opensans11.h"
//#include "font/font2/opensans11b.h"
//#include "font/font2/opensans12.h"
//#include "font/font2/opensans12b.h"
//#include "font/font2/opensans13.h"
//#include "font/font2/opensans13b.h"
//#include "font/font2/opensans14.h"
//#include "font/font2/opensans14b.h"
//#include "font/font2/opensans15.h"
#include "font/font2/opensans16.h"
//#include "font/font2/opensans16b.h"
#include "font/font2/opensans18.h"
#include "font/font2/opensans18b.h"
//#include "font/font2/opensans20.h"
//#include "font/font2/opensans20b.h"
//#include "font/font2/opensans24.h"
//#include "font/font2/opensans24b.h"
//#include "font/font2/opensans26.h"
//#include "font/font2/opensans26b.h"
